### ISSUE TITLE
AuthInterceptor 관련 문제

### ISSUE THREAD

**Issue by 0tak2** [ppiyung/ppiyung-backend#18]
현재 AuthInterceptor는 servelt-context.xml에 URI를 기준으로 맵핑되고 있습니다.
예컨대 인증이 필요하지 않은 URI는 exclude하여 맵핑에서 제외하므로서 세션 존재 여부를 스킵하도록 합니다.

일반적으로 큰 문제가 없으나, #14 풀 리퀘스트와 같이, 같은 URI로 들어오는 요청이나 메서드별로 구분되어야 하는 경우가 있습니다.

- [POST] /member: 회원 생성
- [GET] /member: 회원 조회

POST 요청은 회원 가입에 사용되므로 인증 확인에서 제외되어야 하고, GET 요청은 반드시 인증 확인이 선행되어야 합니다.

우선은 REST에서 약간 벗어나지만, 회원 생성을 /signin에 매핑하여 임시로 문제를 해결한 상황입니다. 어떻게 개선해야 할지 검토해봐야할 것 같습니다.

**Comment by silver-hee** [comment]
네 알겠습니다.

**Comment by 0tak2** [comment]
Spring Security 도입으로 메서드별 매핑이 가능해졌습니다.
